modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="mischief"
version="1.0"
displayName="Mischief"
displayURL="https://youtube.com/@xdec"
logoFile="logo.png"
credits="lesgo"
authors="xdec"
description="this is (not rat's) mischief"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.mischief]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration